In [26]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Disable SSL verification
requests.packages.urllib3.disable_warnings()

# Define the base URL
base_url = "https://bina.az/baki/neriman-nerimanov/alqi-satqi/menziller?page="
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}
# yigilacaq data ucun list yaradiriq
data_list = []

def scrape_page(page_number):
    
    url = base_url + str(page_number)
    response = requests.get(url, verify=False, headers=headers)
    
    if response.status_code == 200:
        # Parse the HTML content of the page
        soup = BeautifulSoup(response.text, 'html.parser')
        
        # arasdirdiq ki items-i ile butun evlere access ede bilirik
        item_i_divs = soup.find_all(class_="items-i")
        
      
        for item_i_div in item_i_divs:
            # card classini tapmaq ucun
            card_params_div = item_i_div.find(class_="card_params")
            
            if card_params_div:
                # Qiymet tagini tapaq
                price_div = card_params_div.find(class_="price")

                span_elements = price_div.find_all("span")
                price_values = [span.text.strip() for span in span_elements]
                
                # m2 otaq sayi ve metebe melumati
                ul_elements = card_params_div.find_all("ul")
                
                # Extract the text content of the ul elements
                ul_values = [ul.text.strip() for ul in ul_elements]
                
                # adress ve saat  melumatlarini toplayaq
                city_when = card_params_div.find(class_='city_when')
                city_when_value = city_when.text.strip() if city_when else ""
                
                # Dictionary yaradiriq
                data_dict = {
                    "Price": price_values,
                    "UL_Values": ul_values,
                    "City_When": city_when_value
                }
                
                # Yigilian melumatlari liste elave edirik
                data_list.append(data_dict)
             

# 1 ci sehifeden baslayaraq
start_page = 1
# 20 qoy yoxla
end_page = 3  # bunu deyisdirib istenilen qeder sehife gezmek olar

# istenilen qeder sehife gezmek
for page_number in range(start_page, end_page + 1):
    print(f"bu deqiqe sehife :  {page_number}:")
    scrape_page(page_number)
    print("\n")
print('Proses bitdi')

# en son dataframe e ceviririk toplanilan datani
df = pd.DataFrame(data_list)

bu deqiqe sehife :  1:


bu deqiqe sehife :  2:


bu deqiqe sehife :  3:


Proses bitdi

In [27]:
df['price'] = [str(i[0]).replace(' ','') for i in df.Price]
df['currency'] = [str(i[1]) for i in df.Price]
df.drop('Price',axis=1,inplace=True)

In [28]:
df['city'] = [i.split(',')[0] for i in df.City_When]
df['date'] = [i.split(',')[1] for i in df.City_When]
df.drop('City_When',axis=1,inplace=True)

In [29]:
df['rooms'] = [i[0][:8] for i in df.UL_Values]
df['size_m2'] = [i[0][8:11] for i in df.UL_Values]
df['floor'] = [i[0][-10:] for i in df.UL_Values]
df.drop('UL_Values',axis=1,inplace=True)

In [30]:
df

     price currency  city          date     rooms size_m2       floor
0   340000      AZN  Bakı   bugün 12:01  3 otaqlı     105  19 mərtəbə
1   400000      AZN  Bakı   dünən 19:07  3 otaqlı     146  16 mərtəbə
2   500000      AZN  Bakı   bugün 13:58  3 otaqlı     127  17 mərtəbə
3   195000      AZN  Bakı   bugün 12:19  2 otaqlı     83   /9 mərtəbə
4   170000      AZN  Bakı   bugün 17:42  3 otaqlı     70   14 mərtəbə
..     ...      ...   ...           ...       ...     ...         ...
79  185000      AZN  Bakı   bugün 15:21  3 otaqlı     85   /4 mərtəbə
80  188000      AZN  Bakı   bugün 15:18  2 otaqlı     75   18 mərtəbə
81  300000      AZN  Bakı   bugün 15:18  3 otaqlı     97   /9 mərtəbə
82  175000      AZN  Bakı   bugün 15:18  2 otaqlı     72   12 mərtəbə
83  360000      AZN  Bakı   bugün 15:41  3 otaqlı     105  17 mərtəbə

[84 rows x 7 columns]